// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qjnppcfbywfazwolfppo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqbnBwY2ZieXdmYXp3b2xmcHBvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNDA0MzksImV4cCI6MjA2MTcxNjQzOX0.1dPuqM42ASnYsfdBs4d2bLRgHxJQzmCSEW2dIUbcJOI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);